### ISSUE TITLE
is there is a plan to release Motion capture data in generate_dataset.py?

### ISSUE THREAD

**Issue by 321hallelujah** [ethanfetaya/NRI#15]
hi,thanks for your really great code!   
it seems you just implement Physics simulations dataset in your code.  i want to apply it to reasoning in video/image, and i dont know the meaning of npy file. 
'edges_valid_springs5.npy' is (10000,5,5),what dose the last (5,5) mean in video.
'loc_valid_springs5.npy' is (10000,49,2,5),what dose the last(2,5) mean in video.
vel_valid_springs5.npy' is (10000,49,2,5),what dose the last(2,5) mean in video.
, and can those nodes be output of regien proposal like ROIAlign?
look forward to your reply.

**Comment by ethanfetaya** [comment]
The inputs are not images, but graphs (which you can turn into a image or video if you please)
5x5 in edges is matrix of edge types, the (2,5) in loc and valid is 2 dimensional location or velocity for 5 objects.

**Comment by 321hallelujah** [comment]
got it! thanks a lot.
