### ISSUE TITLE
'args' is an undefined name in utils.py

### ISSUE THREAD

**Issue by cclauss** [ethanfetaya/NRI#2]
flake8 testing of https://github.com/ethanfetaya/NRI on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./utils.py:459:24: F821 undefined name 'args'
        const = np.log(args.edge_types)
                       ^
```

**Comment by tkipf** [comment]
Thanks for catching this - I'll push a fix ASAP.

**Comment by tkipf** [comment]
Fixed with https://github.com/ethanfetaya/NRI/pull/3 - we only need to wait for @ethanfetaya to merge.
