### ISSUE TITLE
Sport UV dataset

### ISSUE THREAD

**Issue by os1a** [ethanfetaya/NRI#32]
Hi, 

Thanks for your great work,

Can you provide the link or the sport basketball dataset you used in your paper?

You also mentioned that you focused on the PnR instances of the game. How to find these instances?

Best,

**Comment by ethanfetaya** [comment]
Hi @os1a, unfortunantly the sports dataset is proprietary data and we cannot distribute it.

**Comment by os1a** [comment]
Hi, I though that you process the dataset from the following repo:

https://github.com/linouk23/NBA-Player-Movements

Best

**Comment by ethanfetaya** [comment]
Might be based on similar data, but we did not use that repo

**Comment by nshervt** [comment]
@os1a Did you find the basketball dataset used here?
