### ISSUE TITLE
Unsupervised learning 

### ISSUE THREAD

**Issue by karims** [ethanfetaya/NRI#36]
In the Appendix, A.2., unsupervised learning was done:

```To test whether our model can infer an empty graph, we create a test set of 1000 simulations with 5 non-interacting particles and test an unsupervised NRI model which was trained on the spring simulation dataset with 5 particles as before. We find that it achieves an accuracy of 98.4% in identifying ”no interaction” edges (i.e. the empty graph).```

Can someone point out do unsupervised learning from the code in this repo?

**Comment by FatemaMahmoud** [comment]
Hello Karims, did you get the idea?

**Comment by karims** [comment]
@FatemaMahmoud Yes. Its silly. The `train.py` implementation is unsupervised itself. :D It took a while for me to figure out. So, i closed this.

**Comment by FatemaMahmoud** [comment]
So, what should I do with edges files? if I want to run the code on my unlabeled data, should I generate edges with 50% probability to match the edges files?
